server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://mysql.dev.autoai.com:3306/activiti?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: chen
      initial-size: 10
      max-active: 10
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shinley.activiti.entity