server:
  port: 8080
spring:
  datasource:
    username: root
    password: chen
    url:
      url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shinley.activiti.model

# showSql
logging:
  level:
    com:
      shinley:
        activiti:
          mapper:debug